<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BT1704430" failures="1" tests="1" name="TestRunner.Run" time="12.057" errors="0" timestamp="2025-09-11T03:53:39 IST" skipped="0">
  <testcase classname="TestRunner.Run" name="runScenario" time="12.057">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefination.StepDef.user_can_view_confirmation_message(StepDef.java:162)
at âœ½.User can view confirmation message "The new customer has been added successfully."(file:///C:/Users/KIIT/eclipse-workspace-Practice/AutomationProject/CucumberFramework/./Features/Customer.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner.Run -->
